# Generated by Django 2.2.5 on 2019-09-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menubuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
