# Generated by Django 2.2.5 on 2019-09-26 04:47

from django.db import migrations, models
import menubuilder.models


class Migration(migrations.Migration):

    dependencies = [
        ('menubuilder', '0003_auto_20190925_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[(menubuilder.models.MenuType('Menu Label'), 'Menu Label'), (menubuilder.models.MenuType('Menu Option'), 'Menu Option'), (menubuilder.models.MenuType('Entry Input'), 'Entry Input'), (menubuilder.models.MenuType('Dial Ussd Code'), 'Dial Ussd Code')], max_length=10, null=True),
        ),
    ]
