# Generated by Django 2.2.5 on 2019-09-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menubuilder', '0005_auto_20190926_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
