# Generated by Django 2.2.5 on 2019-09-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menubuilder', '0006_auto_20190926_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('LABEL', 'Menu Label'), ('OPTION', 'Menu Option'), ('ENTRY', 'Entry Input'), ('USSDCODE', 'Dial Ussd Code'), ('ROOT', 'Root')], max_length=10, null=True),
        ),
    ]
