# Generated by Django 2.2.5 on 2019-09-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menubuilder', '0007_auto_20190926_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sample_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
